 DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
 DROP TABLE "SNS_POST" CASCADE CONSTRAINTS;
 DROP TABLE "SNS_COMMENT" CASCADE CONSTRAINTS;
 DROP TABLE "HASHTAG" CASCADE CONSTRAINTS;
 DROP TABLE "CATEGORY_PARENT" CASCADE CONSTRAINTS;
 DROP TABLE "CATEGORY_SUB" CASCADE CONSTRAINTS;
 DROP TABLE "BRAND" CASCADE CONSTRAINTS;
 DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
 DROP TABLE "ADDRESS" CASCADE CONSTRAINTS;
 DROP TABLE "ORDER" CASCADE CONSTRAINTS;
 DROP TABLE "ORDER_PRODUCT" CASCADE CONSTRAINTS;
 DROP TABLE "RAFFLE" CASCADE CONSTRAINTS;
 DROP TABLE "SNS_POST_LIKE" CASCADE CONSTRAINTS;
 DROP TABLE "SNS_COMMENT_LIKE" CASCADE CONSTRAINTS;
 DROP TABLE "POST_IMG" CASCADE CONSTRAINTS;
 DROP TABLE "POST_HASHTAG" CASCADE CONSTRAINTS;
 DROP TABLE "FOLLOW" CASCADE CONSTRAINTS;
 DROP TABLE "PRODUCT_DETAIL" CASCADE CONSTRAINTS;
 DROP TABLE "PRODUCT_IMG" CASCADE CONSTRAINTS;
 DROP TABLE "RESELL_STOCK" CASCADE CONSTRAINTS;
 DROP TABLE "STOCK" CASCADE CONSTRAINTS;
 DROP TABLE "SUGGEST" CASCADE CONSTRAINTS;
 DROP TABLE "WISHLIST" CASCADE CONSTRAINTS;
 DROP TABLE "CART" CASCADE CONSTRAINTS;
 DROP TABLE "DELIVERLY" CASCADE CONSTRAINTS;
 DROP TABLE "POINT" CASCADE CONSTRAINTS;
 DROP TABLE "TOTAL_POINT" CASCADE CONSTRAINTS;
 DROP TABLE "CARD" CASCADE CONSTRAINTS;
 DROP TABLE "ACCOUNT" CASCADE CONSTRAINTS;
 DROP TABLE "POST_PRODUCTTAG" CASCADE CONSTRAINTS;
 DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
 DROP TABLE "RAFFLE_MEMBER" CASCADE CONSTRAINTS;
 DROP TABLE "ORDERLIST" CASCADE CONSTRAINTS;
 DROP TABLE "REPORT" CASCADE CONSTRAINTS;
 DROP TABLE "BLACKLIST" CASCADE CONSTRAINTS;
 DROP TABLE "CHAT" CASCADE CONSTRAINTS;

DROP TABLE "INTEREST" CASCADE CONSTRAINTS; -- INTEREST 테이블을 WHISHLIST 테이블 변경으로 인한 기존의 INTEREST 테이블 남아있는 경우의 DROP

-- 회원 테이블
-- DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"USER_ID"	    VARCHAR2(20)	NOT NULL,
	"USER_NAME"	    VARCHAR2(20)	NOT NULL,
	"USER_PWD"	    VARCHAR2(20)	NOT NULL,
	"PHONE" 	    VARCHAR2(11)	NOT NULL,
	"BIRTH" 	    DATE		    NOT NULL,
	"USER_TYPE"	    CHAR(1)	        DEFAULT 2   CHECK(USER_TYPE IN (0,1,2))     NOT NULL,
	"AGREE_EMAIL"	CHAR(1)	        DEFAULT 'N'	CHECK(AGREE_EMAIL IN ('Y','N')) NOT NULL,
	"STATUS"	    CHAR(1)	        DEFAULT 'Y'	CHECK(STATUS IN ('Y','N','X'))      NOT NULL,
	"USER_IMAGE"	VARCHAR2(200)	DEFAULT '/resources/my/img/default_img.png' NOT NULL,
	"INTRODUCE"	    VARCHAR2(300)	NULL,
	"ENROLL_DATE"	DATE	        DEFAULT SYSDATE	    NOT NULL,
	"SNS_ID"	    VARCHAR2(20)    NOT NULL,
	"TOTAL_POINT"	NUMBER	        DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "MEMBER"."USER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."USER_PWD" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."BIRTH" IS '생년월일';

COMMENT ON COLUMN "MEMBER"."USER_TYPE" IS '회원유형(관리자0, 브랜드1,일반2)';

COMMENT ON COLUMN "MEMBER"."AGREE_EMAIL" IS '이메일수신동의(Y, N)';

COMMENT ON COLUMN "MEMBER"."STATUS" IS '계정상태(활성화Y,정지N,탈퇴X)';

COMMENT ON COLUMN "MEMBER"."USER_IMAGE" IS '프로필, SNS 개인이미지';

COMMENT ON COLUMN "MEMBER"."INTRODUCE" IS 'SNS 소개글';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원가입날짜';

COMMENT ON COLUMN "MEMBER"."SNS_ID" IS 'SNS 아이디 기본값 회원아이디';

COMMENT ON COLUMN "MEMBER"."TOTAL_POINT" IS '회원 총 포인트';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_ID"
);

--STYLE게시글 테이블 테이블
-- DROP TABLE "SNS_POST";

CREATE TABLE "SNS_POST" (
	"POST_NO"   	NUMBER		    NOT NULL,
	"USER_ID"   	VARCHAR2(20)	NOT NULL,
	"CONTENT"   	VARCHAR2(100)	NULL,
	"UPROADTIME"	DATE	        DEFAULT SYSDATE NOT NULL,
	"POST_STATUS"	CHAR(1)	        DEFAULT 'Y'     CHECK(POST_STATUS IN ('Y','N')) NOT NULL
);

COMMENT ON COLUMN "SNS_POST"."POST_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "SNS_POST"."USER_ID" IS '회원 아이디(FK)';

COMMENT ON COLUMN "SNS_POST"."CONTENT" IS 'SNS 내용';

COMMENT ON COLUMN "SNS_POST"."UPROADTIME" IS '작성시간';

COMMENT ON COLUMN "SNS_POST"."POST_STATUS" IS '게시글 상태(정상Y,삭제N)';

ALTER TABLE "SNS_POST" ADD CONSTRAINT "PK_SNS_POST" PRIMARY KEY (
	"POST_NO"
);

ALTER TABLE "SNS_POST" ADD CONSTRAINT "FK_MEMBER_TO_SNS_POST_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);


-- STYLE게시글 시퀀스
DROP SEQUENCE SEQ_POST_NO;

CREATE SEQUENCE SEQ_POST_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- STYLE게시글 좋아요 테이블
-- DROP TABLE "SNS_POST_LIKE";

CREATE TABLE "SNS_POST_LIKE" (
	"POST_NO"	NUMBER       NOT NULL,
	"USER_ID"	VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN "SNS_POST_LIKE"."POST_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "SNS_POST_LIKE"."USER_ID" IS '회원 아이디(PK)';

ALTER TABLE "SNS_POST_LIKE" ADD CONSTRAINT "PK_SNS_POST_LIKE" PRIMARY KEY (
	"POST_NO",
	"USER_ID"
);

ALTER TABLE "SNS_POST_LIKE" ADD CONSTRAINT "FK_SNS_POST_TO_SNS_POST_LIKE_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SNS_POST" (
	"POST_NO"
);

ALTER TABLE "SNS_POST_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_SNS_POST_LIKE_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);


-- STYLE 댓글 테이블
-- DROP TABLE "SNS_COMMENT";

CREATE TABLE "SNS_COMMENT" (
	"C_NO"	        NUMBER		 NOT NULL,
	"USER_ID"	    VARCHAR2(20) NOT NULL,
	"POST_NO"	    NUMBER		 NOT NULL,
	"C_CONTENT"	    VARCHAR2(50) NOT NULL,
	"C_UPROADTIME"	DATE	     DEFAULT SYSDATE    NOT NULL,
	"C_STATUS"	    CHAR(1)	     DEFAULT 'Y'        CHECK(C_STATUS IN ('Y','N')) NOT NULL
);

COMMENT ON COLUMN "SNS_COMMENT"."C_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "SNS_COMMENT"."USER_ID" IS '회원 아이디(FK)';

COMMENT ON COLUMN "SNS_COMMENT"."POST_NO" IS '게시글번호(FK)';

COMMENT ON COLUMN "SNS_COMMENT"."C_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "SNS_COMMENT"."C_UPROADTIME" IS '작성시간';

COMMENT ON COLUMN "SNS_COMMENT"."C_STATUS" IS '댓글상태(정상Y,삭제N)';

ALTER TABLE "SNS_COMMENT" ADD CONSTRAINT "PK_SNS_COMMENT" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "SNS_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_SNS_COMMENT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES MEMBER (
	"USER_ID"
);

ALTER TABLE "SNS_COMMENT" ADD CONSTRAINT "FK_SNS_POST_TO_SNS_COMMENT_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SNS_POST" (
	"POST_NO"
);

-- STYLE댓글 시퀀스
DROP SEQUENCE SEQ_POST_CNO;
 
CREATE SEQUENCE SEQ_POST_CNO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- 댓글 좋아요 테이블
-- DROP TABLE "SNS_COMMENT_LIKE";

CREATE TABLE "SNS_COMMENT_LIKE" (
	"C_NO"	    NUMBER		    NOT NULL,
	"USER_ID"	VARCHAR2(20)    NOT NULL
);

COMMENT ON COLUMN "SNS_COMMENT_LIKE"."C_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "SNS_COMMENT_LIKE"."USER_ID" IS '회원 아이디(PK)';

ALTER TABLE "SNS_COMMENT_LIKE" ADD CONSTRAINT "PK_SNS_COMMENT_LIKE" PRIMARY KEY (
	"C_NO",
	"USER_ID"
);

ALTER TABLE "SNS_COMMENT_LIKE" ADD CONSTRAINT "FK_SNS_C_TO_SNS_C_LIKE" FOREIGN KEY (
	"C_NO"
)
REFERENCES "SNS_COMMENT" (
	"C_NO"
);

ALTER TABLE "SNS_COMMENT_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_SNS_C_LIKE" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);


-- STYLE 이미지 테이블
-- DROP TABLE "POST_IMG";

CREATE TABLE "POST_IMG" (
	"IMG_NO"	    NUMBER		    NOT NULL,
	"POST_NO"	    NUMBER		    NOT NULL,
	"IMG_NAME"	    VARCHAR2(255)	NOT NULL,
	"IMG_PATH"	    VARCHAR2(1000)	NOT NULL,
	"IMG_STATUS"	CHAR(1)	        DEFAULT 'Y' CHECK(IMG_STATUS IN ('Y','N')) NOT NULL
);

COMMENT ON COLUMN "POST_IMG"."IMG_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "POST_IMG"."POST_NO" IS '게시글번호(FK)';

COMMENT ON COLUMN "POST_IMG"."IMG_NAME" IS '업로드시 변경된 이름';

COMMENT ON COLUMN "POST_IMG"."IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "POST_IMG"."IMG_STATUS" IS '이미지 상태(정상Y,수정및삭제N)';

ALTER TABLE "POST_IMG" ADD CONSTRAINT "PK_POST_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "POST_IMG" ADD CONSTRAINT "FK_SNS_POST_TO_POST_IMG_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SNS_POST" (
	"POST_NO"
);


-- STYLE이미지 시퀀스
DROP SEQUENCE SEQ_POST_INO;
 
CREATE SEQUENCE SEQ_POST_INO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- 해쉬태그 테이블
-- DROP TABLE "HASHTAG";

CREATE TABLE "HASHTAG" (
	"HASHTAG_ID"	VARCHAR(20)		NOT NULL
);

COMMENT ON COLUMN "HASHTAG"."HASHTAG_ID" IS '해쉬태그(PK)';

ALTER TABLE "HASHTAG" ADD CONSTRAINT "PK_HASHTAG" PRIMARY KEY (
	"HASHTAG_ID"
);


-- STYLE게시글 해쉬태그 테이블
-- DROP TABLE "POST_HASHTAG";

CREATE TABLE "POST_HASHTAG" (
	"POST_NO"	    NUMBER		NOT NULL,
	"HASHTAG_ID"	VARCHAR(20)	NOT NULL
);

COMMENT ON COLUMN "POST_HASHTAG"."POST_NO" IS '게시글번호(FK)';

COMMENT ON COLUMN "POST_HASHTAG"."HASHTAG_ID" IS '해쉬태그(FK)';

ALTER TABLE "POST_HASHTAG" ADD CONSTRAINT "FK_SNS_POST_TO_POST_HASHTAG_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SNS_POST" (
	"POST_NO"
);

ALTER TABLE "POST_HASHTAG" ADD CONSTRAINT "FK_HASHTAG_TO_POST_HASHTAG_1" FOREIGN KEY (
	"HASHTAG_ID"
)
REFERENCES "HASHTAG" (
	"HASHTAG_ID"
);


-- 팔로우리스트 테이블
-- DROP TABLE "FOLLOW";

CREATE TABLE "FOLLOW" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"FOLLOWER"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "FOLLOW"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "FOLLOW"."FOLLOWER" IS '회원 아이디(PK)';

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
	"USER_ID",
	"FOLLOWER"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_1" FOREIGN KEY (
	"FOLLOWER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);


-- 상위 카테고리 테이블
-- DROP TABLE "CATEGORY_PARENT";

CREATE TABLE "CATEGORY_PARENT" (
	"P_CATEGORY_NO"	    NUMBER		    NOT NULL,
	"P_CATEGORY_NAME"	VARCHAR2(20)	NOT NULL
);

COMMENT ON COLUMN "CATEGORY_PARENT"."P_CATEGORY_NO" IS '카테고리넘버(상위)';

COMMENT ON COLUMN "CATEGORY_PARENT"."P_CATEGORY_NAME" IS '카테고리상위이름(FK)';

ALTER TABLE "CATEGORY_PARENT" ADD CONSTRAINT "PK_PARENT_CATEGORY" PRIMARY KEY (
	"P_CATEGORY_NO"
);


-- 상위 카테고리 시퀀스
DROP SEQUENCE SEQ_PCAT_NO;
 
CREATE SEQUENCE SEQ_PCAT_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- 하위 카테고리 테이블
-- DROP TABLE "CATEGORY_SUB";

CREATE TABLE "CATEGORY_SUB" (
	"SUB_CATEGORY_NO"	NUMBER	    	NOT NULL,
	"P_CATEGORY_NO"	    NUMBER  		NOT NULL,
	"SUB_CATEGORY_NAME"	VARCHAR2(20)	NOT NULL
);

COMMENT ON COLUMN "CATEGORY_SUB"."SUB_CATEGORY_NO" IS '카테고리 넘버(하위)';

COMMENT ON COLUMN "CATEGORY_SUB"."P_CATEGORY_NO" IS '카테고리넘버(상위)';

COMMENT ON COLUMN "CATEGORY_SUB"."SUB_CATEGORY_NAME" IS '카테고리하위이름(FK)';

ALTER TABLE "CATEGORY_SUB" ADD CONSTRAINT "PK_SUB_CATEGORY" PRIMARY KEY (
	"SUB_CATEGORY_NO"
);

ALTER TABLE "CATEGORY_SUB" ADD CONSTRAINT "FK_PARENT_CAT_TO_SUBCAT" FOREIGN KEY (
	"P_CATEGORY_NO"
)
REFERENCES "CATEGORY_PARENT" (
	"P_CATEGORY_NO"
);


-- 하위 카테고리 시퀀스
DROP SEQUENCE SEQ_SCAT_NO;
 
CREATE SEQUENCE SEQ_SCAT_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;
       
       
-- 브랜드 테이블
-- DROP TABLE "BRAND";

-- CREATE TABLE "BRAND" (
-- 	"BRAND_NO"	    NUMBER		    NOT NULL,
-- 	"BRAND_NAME"	VARCHAR2(20)	NOT NULL,
-- 	"LUXULY_CHECK"	CHAR(1)	        CHECK(LUXULY_CHECK IN('Y','N')) NOT NULL
-- );

-- COMMENT ON COLUMN "BRAND"."BRAND_NO" IS '브랜드 넘버';

-- COMMENT ON COLUMN "BRAND"."BRAND_NAME" IS '브랜드명';

-- COMMENT ON COLUMN "BRAND"."LUXULY_CHECK" IS '명품(Y,N)';

-- ALTER TABLE "BRAND" ADD CONSTRAINT "PK_BRAND" PRIMARY KEY (
-- 	"BRAND_NO"
-- );


-- 브랜드 시퀀스
-- DROP SEQUENCE SEQ_BAND_NO;
 
-- CREATE SEQUENCE SEQ_BAND_NO
--        INCREMENT BY 1
--        START WITH 0
--        MINVALUE 0
--        MAXVALUE 9999
--        NOCYCLE
--        NOCACHE;


-- 상품 테이블
--DROP TABLE "PRODUCT";

CREATE TABLE "PRODUCT" (
	"PRODUCT_NAME"	    VARCHAR2(500)	NOT NULL,
	"CATEGORY_NO"	    NUMBER		    NOT NULL,
--	"BRAND_NO"	        NUMBER		    NOT NULL,
    "BRAND_NAME"         VARCHAR2(100)   NOT NULL,
	"COMPANY_PRICE"	    NUMBER		    NOT NULL,
	"PRODUCT_GENDER"	CHAR(1)		    NOT NULL,
	"PRODUCT_WEATHER"	VARCHAR(10)	    NOT NULL,
	"STATUS"	        CHAR(1)	        DEFAULT 'Y'	    NOT NULL
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품이름';

COMMENT ON COLUMN "PRODUCT"."CATEGORY_NO" IS '카테고리 넘버(하위)';

--COMMENT ON COLUMN "PRODUCT"."BRAND_NO" IS '브랜드 넘버';
COMMENT ON COLUMN "PRODUCT"."BRAND_NAME" IS '브랜드 이름';

COMMENT ON COLUMN "PRODUCT"."COMPANY_PRICE" IS '발매가';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_GENDER" IS '남자(M),여자(F),공통(U)';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_WEATHER" IS '맑음(C),흐림(F),눈(S),비(R)';

COMMENT ON COLUMN "PRODUCT"."STATUS" IS '정상(Y),재고없음(N)';

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_NAME"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_CATEGORY_SUB_TO_PRODUCT_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "CATEGORY_SUB" (
	"SUBCATEGORY_NO"
);

--ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_BRAND_TO_PRODUCT_1" FOREIGN KEY (
--	"BRAND_NO"
--)
--REFERENCES "BRAND" (
--	"BRAND_NO"
--);




-- 상품상세 테이블
-- DROP TABLE "PRODUCT_DETAIL";

CREATE TABLE "PRODUCT_DETAIL" (
	"PRODUCT_NAME"	        VARCHAR2(100)	NOT NULL,
	"PRODUCT_CONTENT"	    VARCHAR2(4000)	NOT NULL
);

COMMENT ON COLUMN "PRODUCT_DETAIL"."PRODUCT_NAME" IS '상품이름';


COMMENT ON COLUMN "PRODUCT_DETAIL"."PRODUCT_CONTENT" IS '게시글 상세내용';

ALTER TABLE "PRODUCT_DETAIL" ADD CONSTRAINT "PK_PRODUCT_DETAIL" PRIMARY KEY (
	"PRODUCT_NAME"
);

ALTER TABLE "PRODUCT_DETAIL" ADD CONSTRAINT "FK_P_TO_P_DETAIL" FOREIGN KEY (
	"PRODUCT_NAME"
)
REFERENCES "PRODUCT" (
	"PRODUCT_NAME"
);


-- 상품상세 시퀀스
DROP SEQUENCE SEQ_PRODUCT_DNO;
 
CREATE SEQUENCE SEQ_PRODUCT_DNO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;


-- 상품 이미지 테이블
-- DROP TABLE "PRODUCT_IMG";

CREATE TABLE "PRODUCT_IMG" (
	"IMG_NO"	    NUMBER		    NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(1000)	NOT NULL,
	"IMG_NAME"	    VARCHAR2(255)	NOT NULL,
	"IMG_PATH"	    VARCHAR2(1000)	NOT NULL,
	"IMG_STATUS"	CHAR(1)	        DEFAULT 'Y'	CHECK(IMG_STATUS IN('Y','N')) NOT NULL
);

COMMENT ON COLUMN "PRODUCT_IMG"."IMG_NO" IS '시쿼스자동생성(PK)';

COMMENT ON COLUMN "PRODUCT_IMG"."PRODUCT_NAME" IS '상품이름';

COMMENT ON COLUMN "PRODUCT_IMG"."IMG_NAME" IS '업로드시 변경된 이름';

COMMENT ON COLUMN "PRODUCT_IMG"."IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "PRODUCT_IMG"."IMG_STATUS" IS '이미지 상태(정상Y,수정및삭제N)';

ALTER TABLE "PRODUCT_IMG" ADD CONSTRAINT "PK_PRODUCT_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "PRODUCT_IMG" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_IMG_1" FOREIGN KEY (
	"PRODUCT_NAME"
)
REFERENCES "PRODUCT" (
	"PRODUCT_NAME"
);


-- 상품 이미지 시퀀스
DROP SEQUENCE SEQ_PRODUCT_INO;
 
CREATE SEQUENCE SEQ_PRODUCT_INO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- 재고 테이블(리셀재고, 기업재고 통합 테이블)
-- DROP TABLE "STOCK";

DROP TABLE "STOCK";

CREATE TABLE "STOCK" (
	"STOCK_NO"	    NUMBER		    NOT NULL,
	"USER_ID"	    VARCHAR2(20)	NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(100)	NOT NULL,
	"PRICE"	        NUMBER		    NOT NULL,
	"STOCK"	        NUMBER		    NOT NULL,
	"P_SIZE"	    VARCHAR(20)		NOT NULL,
	"STATUS"	    CHAR(1)	        DEFAULT 0	    NOT NULL,
	"USER_CLASS"	CHAR(1)		    NOT NULL,
    "TRADE_COUNT"   NUMBER          DEFAULT 0       NOT NUlL,
    "SUGGEST_DATE"  SUGGEST_DATE    DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN "STOCK"."STOCK_NO" IS '상품 재고번호(시퀀스)';

COMMENT ON COLUMN "STOCK"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "STOCK"."PRODUCT_NAME" IS '상품이름';

COMMENT ON COLUMN "STOCK"."PRICE" IS '가격';

COMMENT ON COLUMN "STOCK"."STOCK" IS '수량';

COMMENT ON COLUMN "STOCK"."P_SIZE" IS '사이즈';

COMMENT ON COLUMN "STOCK"."STATUS" IS '판매대기(0), 판매중(1), 판매완료(2)';

COMMENT ON COLUMN "STOCK"."USER_CLASS" IS '기업회원(1), 일반회원(2)';

COMMENT ON COLUMN "STOCK"."TRADE_COUNT" IS '판매된 상품갯수';

COMMENT ON COLUMN "STOCK"."SUGGEST_DATE" IS '등록일';

ALTER TABLE "STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY (
	"STOCK_NO"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "FK_MEMBER_TO_STOCK_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "FK_PRODUCT_TO_STOCK_1" FOREIGN KEY (
	"PRODUCT_NAME"
)
REFERENCES "PRODUCT" (
	"PRODUCT_NAME"
);

-- 재고 시퀀스
DROP SEQUENCE SEQ_STOCK_NO;
 
CREATE SEQUENCE SEQ_STOCK_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;



-- 리셀 재고 테이블(구 리셀 재고 테이블)
-- DROP TABLE "RESELL_STOCK";

--CREATE TABLE "RESELL_STOCK" (
--	"RESELL_NO"	    NUMBER		    NOT NULL,
--	"PRODUCT_NAME"	VARCHAR2(100)	NOT NULL,
--	"USER_ID"	    VARCHAR2(20)	NOT NULL,
--	"RESELL_PRICE"	NUMBER		    NOT NULL,
--	"STOCK"	        NUMBER		    NOT NULL,
--	"SIZE"	        VARCHAR2(20)	NOT NULL
--);
--
--COMMENT ON COLUMN "RESELL_STOCK"."RESELL_NO" IS '시퀀스자동생성(PK)';
--
--COMMENT ON COLUMN "RESELL_STOCK"."PRODUCT_NAME" IS '상품이름';
--
--COMMENT ON COLUMN "RESELL_STOCK"."USER_ID" IS '회원 아이디(FK)';
--
--COMMENT ON COLUMN "RESELL_STOCK"."RESELL_PRICE" IS '리셀러 판매가격';
--
--COMMENT ON COLUMN "RESELL_STOCK"."STOCK" IS '재고수량';
--
--COMMENT ON COLUMN "RESELL_STOCK"."SIZE" IS '사이즈';
--
--ALTER TABLE "RESELL_STOCK" ADD CONSTRAINT "PK_RESELL STOCK" PRIMARY KEY (
--	"RESELL_NO",
--	"PRODUCT_NAME"
--);
--
--ALTER TABLE "RESELL_STOCK" ADD CONSTRAINT "FK_PRODUCT_TO_RESELL STOCK_1" FOREIGN KEY (
--	"PRODUCT_NAME"
--)
--REFERENCES "PRODUCT" (
--	"PRODUCT_NAME"
--);
--
--ALTER TABLE "RESELL_STOCK" ADD CONSTRAINT "FK_MEMBER_TO_RESELL STOCK_1" FOREIGN KEY (
--	"USER_ID"
--)
--REFERENCES "MEMBER" (
--	"USER_ID"
--);
--
--
---- 리셀 재고 시퀀스
--DROP SEQUENCE SEQ_RESELL_STOCK_NO;
-- 
--CREATE SEQUENCE SEQ_RESELL_STOCK_NO
--       INCREMENT BY 1
--       START WITH 0
--       MINVALUE 0
--       MAXVALUE 9999
--       NOCYCLE
--       NOCACHE;
       
       
-- 재고 테이블(구 재고 테이블)
-- DROP TABLE "STOCK";

--CREATE TABLE "STOCK" (
--	"STOCK_NO"	    NUMBER		    NOT NULL,
--	"PRODUCT_NAME"	VARCHAR2(100)	NOT NULL,
--	"STOCK"	        NUMBER		    NOT NULL,
--	"SIZE"	        VARCHAR2(20)	NOT NULL
--);
--
--COMMENT ON COLUMN "STOCK"."STOCK_NO" IS '재고 넘버';
--
--COMMENT ON COLUMN "STOCK"."PRODUCT_NAME" IS '상품이름';
--
--COMMENT ON COLUMN "STOCK"."STOCK" IS '재고수량';
--
--COMMENT ON COLUMN "STOCK"."SIZE" IS '사이즈';
--
--ALTER TABLE "STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY (
--	"STOCK_NO"
--);
--
--ALTER TABLE "STOCK" ADD CONSTRAINT "FK_PRODUCT_TO_STOCK_1" FOREIGN KEY (
--	"PRODUCT_NAME"
--)
--REFERENCES "PRODUCT" (
--	"PRODUCT_NAME"
--);
--
--
---- 재고 시퀀스
--DROP SEQUENCE SEQ_STOCK_NO;
-- 
--CREATE SEQUENCE SEQ_STOCK_NO
--       INCREMENT BY 1
--       START WITH 0
--       MINVALUE 0
--       MAXVALUE 9999
--       NOCYCLE
--       NOCACHE;
--
--
---- 판매제안서 테이블
---- DROP TABLE "SUGGEST";
--
--CREATE TABLE "SUGGEST" (
--	"SUGGEST_NO"	NUMBER		    NOT NULL,
--	"USER_ID"	    VARCHAR2(20)	NOT NULL,
--	"SUGGEST_BRAND"	VARCHAR2(20)	NOT NULL,
--	"SUGGEST_NAME"	VARCHAR2(20)	NOT NULL,
--	"SUGGEST_PRICE"	NUMBER		    NOT NULL,
--	"SUGGEST_SIZE"	VARCHAR2(20)	NOT NULL,
--	"SUGGEST_COUNT"	NUMBER		    NOT NULL
--);
--
--COMMENT ON COLUMN "SUGGEST"."SUGGEST_NO" IS '시퀀스자동생성(PK)';
--
--COMMENT ON COLUMN "SUGGEST"."USER_ID" IS '회원 아이디(FK)';
--
--ALTER TABLE "SUGGEST" ADD CONSTRAINT "PK_SUGGEST" PRIMARY KEY (
--	"SUGGEST_NO"
--);
--
--ALTER TABLE "SUGGEST" ADD CONSTRAINT "FK_MEMBER_TO_SUGGEST_1" FOREIGN KEY (
--	"USER_ID"
--)
--REFERENCES "MEMBER" (
--	"USER_ID"
--);
--
--
---- 판매제안서 시퀀스
--DROP SEQUENCE SEQ_SUGGEST_NO;
-- 
--CREATE SEQUENCE SEQ_SUGGEST_NO
--       INCREMENT BY 1
--       START WITH 0
--       MINVALUE 0
--       MAXVALUE 9999
--       NOCYCLE
--       NOCACHE;
       
       
-- 관심상품 테이블
-- DROP TABLE "WISHLIST";

CREATE TABLE "WISHLIST" (
	"USER_ID"	    VARCHAR2(20)		NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "WISHLIST"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "WISHLIST"."PRODUCT_NAME" IS '상품이름';

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"USER_ID",
	"PRODUCT_NAME"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_TO_WISHLIST_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_PRODUCT_TO_WISHLIST_1" FOREIGN KEY (
	"PRODUCT_NAME"
)
REFERENCES "PRODUCT" (
	"PRODUCT_NAME"
);


-- (구)장바구니
-- DROP TABLE "CART";

--CREATE TABLE "CART" (
--	"CART_NO"	NUMBER		NOT NULL,
--	"STOCK_NO"	NUMBER		NOT NULL,
--	"USER_ID"	VARCHAR2(20)		NOT NULL,
--	"CART_COUNT"	NUMBER		NOT NULL
--);
--
--COMMENT ON COLUMN "CART"."CART_NO" IS '장바구니';
--
--COMMENT ON COLUMN "CART"."STOCK_NO" IS '상품 재고번호(시퀀스)';
--
--COMMENT ON COLUMN "CART"."USER_ID" IS '로그인 회원 아이디(PK)';
--
--COMMENT ON COLUMN "CART"."CART_COUNT" IS '상품수량';
--
--ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
--	"CART_NO"
--);
--
--ALTER TABLE "CART" ADD CONSTRAINT "FK_STOCK_TO_CART_1" FOREIGN KEY (
--	"STOCK_NO"
--)
--REFERENCES "STOCK" (
--	"STOCK_NO"
--);
--
--ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY (
--	"USER_ID"
--)
--REFERENCES "MEMBER" (
--	"USER_ID"
--);



--DROP TABLE "CART";

CREATE TABLE "CART" (
	"CART_NO"	    NUMBER		    NOT NULL,
	"USER_ID"	    VARCHAR2(20)	NOT NULL,
	"STOCK_NO"	    NUMBER		    NOT NULL,
	"CART_COUNT"	NUMBER		    NOT NULL
);

COMMENT ON COLUMN "CART"."CART_NO" IS '장바구니';

COMMENT ON COLUMN "CART"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "CART"."STOCK_NO" IS '재고 넘버';

COMMENT ON COLUMN "CART"."CART_COUNT" IS '상품수량';

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_NO",
	"USER_ID",
	"STOCK_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_STOCK(2)_TO_CART_1" FOREIGN KEY (
	"STOCK_NO"
)
REFERENCES "STOCK(2)" (
	"STOCK_NO"
);



-- 장바구니 시퀀스
DROP SEQUENCE SEQ_CART_NO;
 
CREATE SEQUENCE SEQ_CART_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;


-- 주소록 테이블
-- DROP TABLE "ADDRESS";

CREATE TABLE "ADDRESS" (
	"ADDRESS_NO"	    NUMBER	        	NOT NULL,
	"USER_ID"	        VARCHAR2(20)		NOT NULL,
	"RECEIVER"	        VARCHAR2(20)		NOT NULL,
	"PHONE"	            VARCHAR2(11)		NOT NULL,
	"POSTCODE"	        NUMBER		        NOT NULL,
	"ADDRESS"	        VARCHAR2(100)		NOT NULL,
	"DEFAULT_ADDRESS"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "ADDRESS"."ADDRESS_NO" IS '주소지 넘버';

COMMENT ON COLUMN "ADDRESS"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "ADDRESS"."RECEIVER" IS '수령인';

COMMENT ON COLUMN "ADDRESS"."PHONE" IS '수령인 번호';

COMMENT ON COLUMN "ADDRESS"."POSTCODE" IS '우편번호';

COMMENT ON COLUMN "ADDRESS"."ADDRESS" IS '주소지';

COMMENT ON COLUMN "ADDRESS"."DEFAULT_ADDRESS" IS '기본배송지(Y),그 외(N)';

ALTER TABLE "ADDRESS" ADD CONSTRAINT "PK_ADDRESS" PRIMARY KEY (
	"ADDRESS_NO"
);

ALTER TABLE "ADDRESS" ADD CONSTRAINT "FK_MEMBER_TO_ADDRESS_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

-- 주소록 시퀀스
DROP SEQUENCE SEQ_ADDRESS_NO;
 
CREATE SEQUENCE SEQ_ADDRESS_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;


-- 주문 테이블
DROP TABLE "ORDER";

CREATE TABLE "ORDER" (
	"ORDER_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"ADDRESS_NO"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TOTAL_AMOUNT"	NUMBER		NOT NULL,
    "POINT"         NUMBER      NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NO" IS '주문번호(PK, 시퀀스)';

COMMENT ON COLUMN "ORDER"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "ORDER"."ADDRESS_NO" IS '주소지 넘버';

COMMENT ON COLUMN "ORDER"."ORDER_DATE" IS '주문일';

COMMENT ON COLUMN "ORDER"."TOTAL_AMOUNT" IS '총 금액';

COMMENT ON COLUMN "ORDER"."POINT" IS '적립 포인트';

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_MEMBER_TO_ORDER_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_ADDRESS_TO_ORDER_1" FOREIGN KEY (
	"ADDRESS_NO"
)
REFERENCES "ADDRESS" (
	"ADDRESS_NO"
);


-- 주문 시퀀스
DROP SEQUENCE SEQ_ORDER_NO;
 
CREATE SEQUENCE SEQ_ORDER_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;
       
   
-- 주문 상품 테이블       
--DROP TABLE "ORDER_PRODUCT";

CREATE TABLE "ORDER_PRODUCT" (
	"ORDER_PNO"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"STOCK_NO"	NUMBER		NOT NULL,
	"ORDER_COUNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ORDER_PRODUCT"."ORDER_PNO" IS '주문상품번호(PK, 시퀀스)';

COMMENT ON COLUMN "ORDER_PRODUCT"."ORDER_NO" IS '주문번호(PK, 시퀀스)';

COMMENT ON COLUMN "ORDER_PRODUCT"."STOCK_NO" IS '시퀀스';

COMMENT ON COLUMN "ORDER_PRODUCT"."ORDER_COUNT" IS '주문된 상품수량';

ALTER TABLE "ORDER_PRODUCT" ADD CONSTRAINT "PK_ORDER_PRODUCT" PRIMARY KEY (
	"ORDER_PNO",
	"ORDER_NO"
);

ALTER TABLE "ORDER_PRODUCT" ADD CONSTRAINT "FK_ORDER_TO_ORDER_PRODUCT_1" FOREIGN KEY (
	"ORDER_NO"
)
REFERENCES "ORDER" (
	"ORDER_NO"
);

ALTER TABLE "ORDER_PRODUCT" ADD CONSTRAINT "FK_STOCK_TO_ORDER_PRODUCT_1" FOREIGN KEY (
	"STOCK_NO"
)
REFERENCES "STOCK" (
	"STOCK_NO"
);

       
DROP SEQUENCE SEQ_ORDER_PNO;
 
CREATE SEQUENCE SEQ_ORDER_PNO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;        
       
       
-- 배송 테이블
--DROP TABLE "DELIVERLY";

CREATE TABLE "DELIVERLY" (
	"DELIVERLY_NO"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"DELIVERY_DATE"	DATE		NOT NULL,
	"DELIVERY_COMPANY"	VARCHAR(20)		NOT NULL,
	"TRACKING_NUMBER"	NUMBER		NOT NULL,
	"TRACKING_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "DELIVERLY"."DELIVERLY_NO" IS '배송번호(PK)_시퀀스';

COMMENT ON COLUMN "DELIVERLY"."ORDER_NO" IS '주문번호(PK, 시퀀스)';

COMMENT ON COLUMN "DELIVERLY"."DELIVERY_DATE" IS '배송일자';

COMMENT ON COLUMN "DELIVERLY"."DELIVERY_COMPANY" IS '배송업체';

COMMENT ON COLUMN "DELIVERLY"."TRACKING_NUMBER" IS '운송장번호';

COMMENT ON COLUMN "DELIVERLY"."TRACKING_DATE" IS '송장입력일자';

ALTER TABLE "DELIVERLY" ADD CONSTRAINT "PK_DELIVERLY" PRIMARY KEY (
	"DELIVERLY_NO"
);

ALTER TABLE "DELIVERLY" ADD CONSTRAINT "FK_ORDER_TO_DELIVERLY_1" FOREIGN KEY (
	"ORDER_NO"
)
REFERENCES "ORDER" (
	"ORDER_NO"
);


-- 배송 시퀀스
DROP SEQUENCE SEQ_DELIVERLY_NO;
 
CREATE SEQUENCE SEQ_DELIVERLY_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;


-- 카드 테이블
--DROP TABLE "CARD";

CREATE TABLE "CARD" (
	"USER_ID"	    VARCHAR2(20)	NOT NULL,
	"CARD_NO"	    NUMBER		    NOT NULL,
	"CARD_PWD"	    NUMBER		    NOT NULL,
	"CARD_VALIDITY"	DATE		    NOT NULL,
	"CVC"	        NUMBER		    NOT NULL
);

COMMENT ON COLUMN "CARD"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "CARD"."CARD_NO" IS '카드번호';

COMMENT ON COLUMN "CARD"."CARD_PWD" IS '카드비밀번호(2 자리)';

COMMENT ON COLUMN "CARD"."CARD_Validity" IS '카드유효기간(YY/MM)';

COMMENT ON COLUMN "CARD"."CVC" IS 'CVC(3자리';

ALTER TABLE "CARD" ADD CONSTRAINT "PK_CARD" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "CARD" ADD CONSTRAINT "FK_MEMBER_TO_CARD_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);


-- 계좌 테이블
--DROP TABLE "ACCOUNT";

CREATE TABLE "ACCOUNT" (
	"USER_ID"	        VARCHAR2(20)	NOT NULL,
	"BANK_NAME"	        VARCHAR2(30)	NOT NULL,
	"ACCOUNT_NO"	    NUMBER		    NOT NULL,
	"ACCOUNT_HOLDER"    VARCHAR(20)		NOT NULL
);

COMMENT ON COLUMN "ACCOUNT"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "ACCOUNT"."BANK_NAME" IS '은행명';

COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_NO" IS '계좌번호';

COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_HOLDER" IS '예금주';

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "FK_MEMBER_TO_ACCOUNT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

-- 게시글 상품태그
-- DROP TABLE "POST_PRODUCTTAG";

CREATE TABLE "POST_PRODUCTTAG" (
	"POST_PRODUCTTAG_ID"	NUMBER		NOT NULL,
	"POST_NO"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "POST_PRODUCTTAG"."POST_PRODUCTTAG_ID" IS '구매상품태그';

COMMENT ON COLUMN "POST_PRODUCTTAG"."POST_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "POST_PRODUCTTAG"."ORDER_NO" IS '주문번호(PK, 시퀀스)';

ALTER TABLE "POST_PRODUCTTAG" ADD CONSTRAINT "PK_POST_PRODUCTTAG" PRIMARY KEY (
	"POST_PRODUCTTAG_ID"
);

ALTER TABLE "POST_PRODUCTTAG" ADD CONSTRAINT "FK_SNS_POST_TO_POST_PRODUCTTAG_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SNS_POST" (
	"POST_NO"
);

ALTER TABLE "POST_PRODUCTTAG" ADD CONSTRAINT "FK_ORDER_TO_POST_PRODUCTTAG_1" FOREIGN KEY (
	"ORDER_NO"
)
REFERENCES "ORDER" (
	"ORDER_NO"
);


-- 공지사항 테이블
-- DROP TABLE "NOTICE";

CREATE TABLE "NOTICE" (
	"ALERT_NO"	        NUMBER		    NOT NULL,
	"ALERT_CATEGORY"	VARCHAR2(500)	NOT NULL,
	"ALERT_TITLE"   	VARCHAR2(500)	NOT NULL,
	"ALERT_CONTENT" 	VARCHAR2(4000)	NOT NULL,
	"CREATE_DATE"	    DATE	        DEFAULT SYSDATE	    NOT NULL,
    "QLEVEL"             CHAR(1)         CHECK("QLEVEL" IN(0,1)) NOT NULL
);

COMMENT ON COLUMN "NOTICE"."ALERT_NO" IS '공지사항번호(PK)';

COMMENT ON COLUMN "NOTICE"."ALERT_CATEGORY" IS '카테고리';

COMMENT ON COLUMN "NOTICE"."ALERT_TITLE" IS '제목';

COMMENT ON COLUMN "NOTICE"."ALERT_CONTENT" IS '본문';

COMMENT ON COLUMN "NOTICE"."CREATE_DATE" IS '공지사항 작성시간';

COMMENT ON COLUMN "NOTICE"."QLEVEL" IS '공지사항(0), FAQ(1)';

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"ALERT_NO"
);


-- 공지사항 시퀀스
DROP SEQUENCE SEQ_NOTICE_NO;
 
CREATE SEQUENCE SEQ_NOTICE_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- 레플 테이블
-- DROP TABLE "RAFFLE";

CREATE TABLE "RAFFLE" (
	"RAFFLE_NO"	        NUMBER		    NOT NULL,
	"RAFFLE_PRODUCT"	VARCHAR2(100)		NOT NULL,
	"FRFFLE_PRICE"	    NUMBER		    NOT NULL,
	"RAFFLE_COMMENT"	VARCHAR2(200)	NOT NULL,
	"NOTICE"	        VARCHAR2(300)	NOT NULL,
	"RAFFLE_START"	    DATE		    NOT NULL,
	"RAFFLE_END"	    DATE		    NOT NULL,
	"LUCKY_START"	    DATE		    NOT NULL,
	"LUCKY_END"	        DATE		    NOT NULL
);

COMMENT ON COLUMN "RAFFLE"."RAFFLE_NO" IS '레플번호(PK)';

COMMENT ON COLUMN "RAFFLE"."RAFFLE_PRODUCT" IS '상품명';

COMMENT ON COLUMN "RAFFLE"."FRFFLE_PRICE" IS '상품가격';

COMMENT ON COLUMN "RAFFLE"."RAFFLE_COMMENT" IS '설명';

COMMENT ON COLUMN "RAFFLE"."NOTICE" IS '안내사항';

COMMENT ON COLUMN "RAFFLE"."RAFFLE_START" IS '응모시작일';

COMMENT ON COLUMN "RAFFLE"."RAFFLE_END" IS '응모종료일';

COMMENT ON COLUMN "RAFFLE"."LUCKY_START" IS '당첨자 구매시작일';

COMMENT ON COLUMN "RAFFLE"."LUCKY_END" IS '당첨자 구매종료일';

ALTER TABLE "RAFFLE" ADD CONSTRAINT "PK_RAFFLE" PRIMARY KEY (
	"RAFFLE_NO"
);


-- 레플 시퀀스
DROP SEQUENCE SEQ_RAFFLE_NO;
 
CREATE SEQUENCE SEQ_RAFFLE_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;


-- 레플 응모자 테이블
-- DROP TABLE "RAFFLE_MEMBER";

CREATE TABLE "RAFFLE_MEMBER" (
	"USER_ID"	VARCHAR2(20)	NOT NULL,
	"RAFFLE_NO"	NUMBER		    NOT NULL
);

COMMENT ON COLUMN "RAFFLE_MEMBER"."USER_ID" IS '회원 아이디(PK)';

COMMENT ON COLUMN "RAFFLE_MEMBER"."RAFFLE_NO" IS '레플번호(PK)';

ALTER TABLE "RAFFLE_MEMBER" ADD CONSTRAINT "PK_RAFFLE_MEMBER" PRIMARY KEY (
	"USER_ID",
	"RAFFLE_NO"
);

ALTER TABLE "RAFFLE_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_RAFFLE_MEMBER_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "RAFFLE_MEMBER" ADD CONSTRAINT "FK_RAFFLE_TO_RAFFLE_MEMBER_1" FOREIGN KEY (
	"RAFFLE_NO"
)
REFERENCES "RAFFLE" (
	"RAFFLE_NO"
);


-- 주문관리/송금 테이블(? 외래키 안됨)
-- DROP TABLE "ORDERLIST";

CREATE TABLE "ORDERLIST" (
	"ORDER_NO"	    VARCHAR(255)	NOT NULL,
	"RESELL_NO"	    NUMBER		    NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(100)	NOT NULL,
	"ORDER_PAY"	    CHAR(1)	        DEFAULT 'N'	CHECK(ORDER_PAY IN('Y','N'))    NOT NULL
);

COMMENT ON COLUMN "ORDERLIST"."ORDER_NO" IS '주문번호(PK)';

COMMENT ON COLUMN "ORDERLIST"."RESELL_NO" IS '시퀀스자동생성(FK)';

COMMENT ON COLUMN "ORDERLIST"."PRODUCT_NAME" IS '상품이름(FK)';

COMMENT ON COLUMN "ORDERLIST"."ORDER_PAY" IS '송금여부(Y , N)';

ALTER TABLE "ORDERLIST" ADD CONSTRAINT "PK_ORDERLIST" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "ORDERLIST" ADD CONSTRAINT "FK_RESELL STOCK_TO_ORDERLIST_1" FOREIGN KEY (
	"RESELL_NO","PRODUCT_NAME"
)
REFERENCES "RESELL_STOCK" (
	"RESELL_NO","PRODUCT_NAME"
);

--ALTER TABLE "ORDERLIST" ADD CONSTRAINT "FK_RESELL STOCK_TO_ORDERLIST_2" FOREIGN KEY (
--	"PRODUCT_NAME"
--)
--REFERENCES "RESELL_STOCK" (
--	"PRODUCT_NAME"
--);


-- 신고 테이블
-- DROP TABLE "REPORT";

CREATE TABLE "REPORT" (
	"REPORT_NO"	    NUMBER		    NOT NULL,
	"USER_ID"	    VARCHAR2(20)    NOT NULL,
	"POST_NO"	    NUMBER		    NOT NULL,
	"REPORT_REASON"	CHAR(2)		    NOT NULL,
	"REPORT_STATUS"	CHAR(1)		    NOT NULL,
	"CREATE_DATE"	DATE	        DEFAULT SYSDATE	    NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호(PK)';

COMMENT ON COLUMN "REPORT"."USER_ID" IS '작성자';

COMMENT ON COLUMN "REPORT"."POST_NO" IS '시퀀스자동생성(PK)';

COMMENT ON COLUMN "REPORT"."REPORT_REASON" IS '신고사유 (최대 두가지 선택)';

COMMENT ON COLUMN "REPORT"."REPORT_STATUS" IS '신고상태(Y,N,X) X=접수중';

COMMENT ON COLUMN "REPORT"."CREATE_DATE" IS '접수일';

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_SNS_POST_TO_REPORT_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SNS_POST" (
	"POST_NO"
);


-- 신고 시퀀스
DROP SEQUENCE SEQ_REPORT_NO;
 
CREATE SEQUENCE SEQ_REPORT_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;


-- 블랙리스트 테이블
-- DROP TABLE "BLACKLIST";

CREATE TABLE "BLACKLIST" (
	"BlACK_NO"	    NUMBER		 NOT NULL,
	"USER_ID"	    VARCHAR2(20) NOT NULL,
	"BLACK_DATE"	DATE	     DEFAULT SYSDATE	NOT NULL,
	"STATUS"	    CHAR(1)		 NOT NULL
);

COMMENT ON COLUMN "BLACKLIST"."USER_ID" IS '회원 아이디(FK)';

COMMENT ON COLUMN "BLACKLIST"."BLACK_DATE" IS '블랙리스트 등록일';

COMMENT ON COLUMN "BLACKLIST"."STATUS" IS 'Y정지N정상';

ALTER TABLE "BLACKLIST" ADD CONSTRAINT "PK_BLACKLIST" PRIMARY KEY (
	"BlACK_NO"
);

ALTER TABLE "BLACKLIST" ADD CONSTRAINT "FK_MEMBER_TO_BLACKLIST_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);


-- 블랙리스트 시퀀스
DROP SEQUENCE SEQ_BACKLIST_NO;
 
CREATE SEQUENCE SEQ_BACKLIST_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;
       
       
-- 실시간 채팅
-- DROP TABLE "CHAT";

CREATE TABLE "CHAT" (
	"CHATTING_NO"	NUMBER		    NOT NULL,
	"USER_ID"	    VARCHAR2(20)    NOT NULL,
	"CHATTING_MSG"	VARCHAR2(300)	NOT NULL,
	"RECEIVE_ID"	VARCHAR2(20)	NOT NULL,
	"CREATE_DATE"	DATE	        DEFAULT SYSDATE	    NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHATTING_NO" IS '채팅번호(PK)';

COMMENT ON COLUMN "CHAT"."USER_ID" IS '유저 채팅 아이디';

COMMENT ON COLUMN "CHAT"."CHATTING_MSG" IS '채팅 내용';

COMMENT ON COLUMN "CHAT"."RECEIVE_ID" IS '관리자 아이디';

COMMENT ON COLUMN "CHAT"."CREATE_DATE" IS '채팅 작성시간';

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHATTING_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

-- 실시간 채팅 시퀀스
DROP SEQUENCE SEQ_CHAT_NO;
 
CREATE SEQUENCE SEQ_CHAT_NO
       INCREMENT BY 1
       START WITH 0
       MINVALUE 0
       MAXVALUE 9999
       NOCYCLE
       NOCACHE;

-- 상위 카테고리 데이터삽입
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '신발');    
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '아우터');
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '상의');
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '하의');
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '가방');
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '지갑');
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '시계');
INSERT INTO CATEGORY_PARENT(P_CATEGORY_NO, P_CATEGORY_NAME)
    VALUES(SEQ_PCAT_NO.NEXTVAL, '패션잡화');
    
-- 하위 카테고리 데이터삽입
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '스니커즈');      
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '플랫');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '로퍼');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '더비/레이스업');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '샌들/슬리퍼');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '힐/펌프스');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '부츠');  
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 1, '기타 신발');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 2, '자켓');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 2, '코트');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 2, '아노락');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 2, '패딩');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 2, '기타 아우터');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '가디건');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '긴팔 티셔츠');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '반팔 티셔츠');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '셔츠');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '후드');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '후드집업');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '스웨트셔츠');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '슬리브리스');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '원피스');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '니트');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 3, '기타 상의');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 4, '바지');     
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 4, '반바지');     
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 4, '스커트');         
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 4, '레깅스');         
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 4, '기타 하의');      
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '프리미엄가방');             
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '미니백');         
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '백팩');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '숄더백');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '토트백');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '크로스백');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '클러치');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '더플백');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '에코백');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '캐리어');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 5, '기타 가방');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 6, '반지갑');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 6, '장지갑');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 6, '카드 지갑');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 6, '체인 지갑');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 6, '기타 지갑');
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 7, '프리미엄시계');    
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 7, '전자 시계');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 7, '가죽 시계');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 7, '메탈 시계');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 7, '기타 시계');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '귀걸이');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '목걸이');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '팔찌');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '반지');        
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '기타 주얼리');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '비니');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '버킷햇');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '볼캡');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '기타 모자');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '벨트');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '아이웨어');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '머플러');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '스카프');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '키링');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '넥타이');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '장갑');            
INSERT INTO CATEGORY_SUB(SUB_CATEGORY_NO, P_CATEGORY_NO, SUB_CATEGORY_NAME)
    VALUES(SEQ_SCAT_NO.NEXTVAL, 8, '기타 패션잡화');            
    
-- 테스트 회원 생성
--'admin@naver.com'
INSERT INTO MEMBER(USER_ID, USER_NAME, USER_PWD, PHONE, BIRTH, SNS_ID)
       VALUES ('test@smf.com', '테스트', '1q2w3e4r@', 01011110000, '01/01/01', 'test@smf.com');
       
INSERT INTO MEMBER(USER_ID, USER_NAME, USER_PWD, PHONE, BIRTH, SNS_ID)
       VALUES  ('admin@naver.com', 'admin', '1q2w3e4r@', 01011110000, '12/12/12', 'admin@naver.com' );
	   
COMMIT;

--SELECT * FROM user_tables;    
SELECT COUNT(*) AS "테이블 개수" FROM user_tables; -- 35개
SELECT COUNT(*) AS "시퀀스 개수" FROM user_sequences; -- 20개